import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import ButtonAppBar from "./components/button-app-bar";
export const metadata: Metadata = {
  title: "Todo List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers><ButtonAppBar></ButtonAppBar>{children}</Providers>
      </body>
    </html>
  );
}
